baseURL = "https://learn.eoscostarica.io/"
languageCode = "en-us"
title = "EOS Learning Resources by EOS Costa Rica"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "eoscostarica"
	description = "A curated list of EOS learning resources."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eoscostarica/eos-learning-resources"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "blue-grey"

  [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "eoscostarica"
	github  = "eoscostarica"
	email   = "bp@eosio.cr"


[[menu.main]]
	name   = "Open Source"
	url    = "open-source/"
	weight = 10

[[menu.main]]
	name   = "Dev Tools"
	url    = "tools/"
	weight = 9

[[menu.main]]
	name   = "EOS Funds"
	url    = "eos-funds/"
	weight = 8

[[menu.main]]
	name   = "DAPP Resource Usage"
	url    = "resource-usage/"
	weight = 6

[[menu.main]]
	name   = "EOS Accounts"
	url    = "eos-accounts/"
	weight = 5

[[menu.main]]
	name   = "Block Producers"
	url    = "block-producer/"
	weight = 4

[[menu.main]]
	name   = "Governance"
	url    = "governance"
	weight = 7

[[menu.main]]
	name   = "Delegated Proof of Stake (DPOS)"
	url    = "delegated-proof-of-stake/"
	weight = 3

[[menu.main]]
	name   = "EOS Blockchain"
	url    = "eos-blockchain/"
	weight = 2

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
